"""add color to lists

Revision ID: 85e4ec1b7f5f
Revises: 5d27e1261995
Create Date: 2026-04-18 22:09:24.672822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85e4ec1b7f5f'
down_revision: Union[str, Sequence[str], None] = '5d27e1261995'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_id'), table_name='items')
    op.create_index(op.f('ix_items_id'), 'items', ['id'], unique=False)
    op.create_foreign_key(None, 'items', 'lists', ['list_id'], ['id'])
    op.drop_column('items', 'color')
    op.add_column('lists', sa.Column('color', sa.String(), nullable=True))
    op.alter_column('lists', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lists', 'name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('lists', 'color')
    op.add_column('items', sa.Column('color', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'items', type_='foreignkey')
    op.drop_index(op.f('ix_items_id'), table_name='items')
    op.create_index(op.f('ix_tasks_id'), 'items', ['id'], unique=False)
    # ### end Alembic commands ###
